const logoList: any[] = [
  {
    label: 'A',
    carlist: [
      {
        id: 'A0',
        engAndChines: 'AODI',
        chineseLabel: '奥迪',
        englishLabel: 'Audi',
        车标: '',
        '': '未找到英文名使用拼音填充',
      },
      {
        id: 'A1',
        engAndChines: 'AERFALUOMIOU',
        chineseLabel: '阿尔法罗密欧',
        englishLabel: 'ALFA ROMEO',
        车标: '',
        '': '',
      },
      {
        id: 'A2',
        engAndChines: 'ANKAIKECHE',
        chineseLabel: '安凯客车',
        englishLabel: 'ANKAI',
        车标: '',
        '': '',
      },
      {
        id: 'A3',
        engAndChines: 'ANYUANKECHE',
        chineseLabel: '安源客车',
        englishLabel: 'Anyuan Bus',
        车标: '',
        '': '',
      },
      {
        id: 'A7',
        engAndChines: 'AITO',
        chineseLabel: 'AITO',
        englishLabel: 'AITO',
        车标: '',
        '': '',
      },
      {
        id: 'A9',
        engAndChines: 'AIAN',
        chineseLabel: '埃安',
        englishLabel: 'AION',
        车标: '',
        '': '',
      },
      {
        id: 'AA',
        engAndChines: 'AICHI',
        chineseLabel: '爱驰',
        englishLabel: 'AIWAYS',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'B',
    carlist: [
      {
        id: 'B0',
        engAndChines: 'BENCHI',
        chineseLabel: '奔驰',
        englishLabel: 'Mercedes-Benz',
        车标: '',
        '': '',
      },
      {
        id: 'B3',
        engAndChines: 'BIEKE',
        chineseLabel: '别克',
        englishLabel: 'BUICK',
        车标: '',
        '': '',
      },
      {
        id: 'B4',
        engAndChines: 'BINLI',
        chineseLabel: '宾利',
        englishLabel: 'BENTLEY',
        车标: '',
        '': '',
      },
      {
        id: 'B5',
        engAndChines: 'BAOMA',
        chineseLabel: '宝马',
        englishLabel: 'BMW',
        车标: '',
        '': '',
      },
      {
        id: 'B6',
        engAndChines: 'BAOSHIJIE',
        chineseLabel: '保时捷',
        englishLabel: 'PORSCHE',
        车标: '',
        '': '',
      },
      {
        id: 'B7',
        engAndChines: 'BENTIAN',
        chineseLabel: '本田',
        englishLabel: 'HONDA',
        车标: '',
        '': '',
      },
      {
        id: 'B8',
        engAndChines: 'BENTENG',
        chineseLabel: '奔腾',
        englishLabel: 'BESTUNE',
        车标: '',
        '': '',
      },
      {
        id: 'B9',
        engAndChines: 'BIYADI',
        chineseLabel: '比亚迪',
        englishLabel: 'BYD',
        车标: '',
        '': '',
      },
      {
        id: 'BA',
        engAndChines: 'BIAOZHI',
        chineseLabel: '标致',
        englishLabel: 'PEUGEOT',
        车标: '',
        '': '',
      },
      {
        id: 'BB',
        engAndChines: 'BEIQIWEIWANG',
        chineseLabel: '北汽威旺',
        englishLabel: 'BAIC Weiwang',
        车标: '',
        '': '',
      },
      {
        id: 'BC',
        engAndChines: 'BAOJUN',
        chineseLabel: '宝骏',
        englishLabel: 'BAOJUN',
        车标: '',
        '': '',
      },
      {
        id: 'BD',
        engAndChines: 'BEIQIHUANSU',
        chineseLabel: '北汽幻速',
        englishLabel: 'BAIC Huansu',
        车标: '',
        '': '',
      },
      {
        id: 'BE',
        engAndChines: 'BAOSHI',
        chineseLabel: '宝石',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'BF',
        engAndChines: 'BEIJING',
        chineseLabel: '北京',
        englishLabel: 'BAIC MOTOR',
        车标: '',
        '': '',
      },
      {
        id: 'BG',
        engAndChines: 'BEIBENZHONGKA',
        chineseLabel: '北奔重卡',
        englishLabel: 'BEIBEN TRUCK',
        车标: '',
        '': '',
      },
      {
        id: 'BH',
        engAndChines: 'BEIFANGKECHE',
        chineseLabel: '北方客车',
        englishLabel: 'BEIFANG BUS',
        车标: '',
        '': '',
      },
      {
        id: 'BI',
        engAndChines: 'BENMA',
        chineseLabel: '奔马',
        englishLabel: 'Benma',
        车标: '',
        '': '',
      },
      {
        id: 'BJ',
        engAndChines: 'BEIQIZHIZAO',
        chineseLabel: '北汽制造',
        englishLabel: 'BAW',
        车标: '',
        '': '',
      },
      {
        id: 'BK',
        engAndChines: 'BABOSI',
        chineseLabel: '巴博斯',
        englishLabel: 'BRABUS',
        车标: '',
        '': '',
      },
      {
        id: 'BL',
        engAndChines: 'BAOQI',
        chineseLabel: '宝骐',
        englishLabel: 'BOIDGE',
        车标: '',
        '': '',
      },
      {
        id: 'BM',
        engAndChines: 'BAOWO',
        chineseLabel: '宝沃',
        englishLabel: 'BORGWARD',
        车标: '',
        '': '',
      },
      {
        id: 'BN',
        engAndChines: 'BEIQIDAODA',
        chineseLabel: '北汽道达',
        englishLabel: 'BAIC DAODA',
        车标: '',
        '': '',
      },
      {
        id: 'BO',
        engAndChines: 'BISU',
        chineseLabel: '比速',
        englishLabel: 'BISU',
        车标: '',
        '': '',
      },
      {
        id: 'BQ',
        engAndChines: 'BUJIADI',
        chineseLabel: '布加迪',
        englishLabel: 'BUGATTI',
        车标: '',
        '': '',
      },
      {
        id: 'BR',
        engAndChines: 'BAIZHIXINNENGYUAN',
        chineseLabel: '百智新能源',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'BS',
        engAndChines: 'BEIQIRUIXIANG',
        chineseLabel: '北汽瑞翔',
        englishLabel: 'BAIC RUIXIANG',
        车标: '',
        '': '',
      },
      {
        id: 'BU',
        engAndChines: 'BIKEQICHE',
        chineseLabel: '比克汽车',
        englishLabel: 'BAK AUTOMOBILE',
        车标: '',
        '': '',
      },
      {
        id: 'BX',
        engAndChines: 'BEIQICHANGHE',
        chineseLabel: '北汽昌河',
        englishLabel: 'BAIC CHANGHE',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'C',
    carlist: [
      {
        id: 'C0',
        engAndChines: 'CHANGAN',
        chineseLabel: '长安',
        englishLabel: 'CHANGAN',
        车标: '',
        '': '',
      },
      {
        id: 'C1',
        engAndChines: 'CHANGCHENG',
        chineseLabel: '长城',
        englishLabel: 'GREAT WALL',
        车标: '',
        '': '',
      },
      {
        id: 'C2',
        engAndChines: 'CHANGFENG',
        chineseLabel: '长丰',
        englishLabel: 'CHANGFENG',
        车标: '',
        '': '',
      },
      {
        id: 'C8',
        engAndChines: 'CHANGANOUSHANG',
        chineseLabel: '长安欧尚',
        englishLabel: 'CHANGAN OSHAN',
        车标: '',
        '': '',
      },
      {
        id: 'C9',
        engAndChines: 'CHENGGONG',
        chineseLabel: '成功',
        englishLabel: 'Victory',
        车标: '',
        '': '',
      },
      {
        id: 'CA',
        engAndChines: 'CHUFENG',
        chineseLabel: '楚风',
        englishLabel: 'CHUFENG',
        车标: '',
        '': '',
      },
      {
        id: 'CF',
        engAndChines: 'CHENGSHI',
        chineseLabel: '橙仕',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'CG',
        engAndChines: 'CHUANGWEIQICHE',
        chineseLabel: '创维汽车',
        englishLabel: 'SKYWORTH',
        车标: '',
        '': '',
      },
      {
        id: 'CH',
        engAndChines: 'CHANGANSHENLAN',
        chineseLabel: '长安深蓝',
        englishLabel: 'DEEPAL',
        车标: '',
        '': '',
      },
      {
        id: 'CP',
        engAndChines: 'CHANGANKAICHENG',
        chineseLabel: '长安凯程',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'D',
    carlist: [
      {
        id: 'D0',
        engAndChines: 'DONGFENG',
        chineseLabel: '东风',
        englishLabel: 'DONGFENG',
        车标: '',
        '': '',
      },
      {
        id: 'D1',
        engAndChines: 'DAFA',
        chineseLabel: '大发',
        englishLabel: 'DAIHATSU',
        车标: '',
        '': '',
      },
      {
        id: 'D2',
        engAndChines: 'DONGFENGFENGSHEN',
        chineseLabel: '东风风神',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'D4',
        engAndChines: 'DONGNAN',
        chineseLabel: '东南',
        englishLabel: 'SOUEAST',
        车标: '',
        '': '',
      },
      {
        id: 'D5',
        engAndChines: 'DAOQI',
        chineseLabel: '道奇',
        englishLabel: 'DODGE',
        车标: '',
        '': '',
      },
      {
        id: 'D6',
        engAndChines: 'DAZHONG',
        chineseLabel: '大众',
        englishLabel: 'Volkswagen',
        车标: '',
        '': '',
      },
      {
        id: 'D7',
        engAndChines: 'DAYU',
        chineseLabel: '大宇',
        englishLabel: 'DAEWOO',
        车标: '',
        '': '',
      },
      {
        id: 'D8',
        engAndChines: 'DONGFENGLIUQI',
        chineseLabel: '东风柳汽',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'D9',
        engAndChines: 'DAYUN',
        chineseLabel: '大运',
        englishLabel: 'Dayun',
        车标: '',
        '': '',
      },
      {
        id: 'DB',
        engAndChines: 'DONGFENGRICHANCHAI',
        chineseLabel: '东风日产柴',
        englishLabel: 'UD TRUCKS',
        车标: '',
        '': '',
      },
      {
        id: 'DC',
        engAndChines: 'DONGFANGHONG',
        chineseLabel: '东方红',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'DE',
        engAndChines: 'DS',
        chineseLabel: 'DS',
        englishLabel: 'DS',
        车标: '',
        '': '',
      },
      {
        id: 'DF',
        engAndChines: 'DACIA',
        chineseLabel: '达西亚',
        englishLabel: 'DACIA',
        车标: '',
        '': '',
      },
      {
        id: 'DG',
        engAndChines: 'DATSUN',
        chineseLabel: '达特桑',
        englishLabel: 'DATSUN',
        车标: '',
        '': '',
      },
      {
        id: 'DI',
        engAndChines: 'DIANKA',
        chineseLabel: '电咖',
        englishLabel: 'DEARCC',
        车标: '',
        '': '',
      },
      {
        id: 'DP',
        engAndChines: 'DONGFENGFENGGUANG',
        chineseLabel: '东风风光',
        englishLabel: 'FENCON',
        车标: '',
        '': '',
      },
      {
        id: 'DQ',
        engAndChines: 'DONGFENGFENGXING',
        chineseLabel: '东风风行',
        englishLabel: 'FORTHING',
        车标: '',
        '': '',
      },
      {
        id: 'DR',
        engAndChines: 'DONGFENGFUKANG',
        chineseLabel: '东风富康',
        englishLabel: 'Fukang',
        车标: '',
        '': '',
      },
      {
        id: 'D1A',
        engAndChines: 'DIANDONGWU',
        chineseLabel: '电动屋',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
    ],
  },
  // {
  //     label:"E",
  //     carlist:[

  //     ]
  // },
  {
    label: 'F',
    carlist: [
      {
        id: 'F1',
        engAndChines: 'FALALI',
        chineseLabel: '法拉利',
        englishLabel: 'Ferrari',
        车标: '',
        '': '',
      },
      {
        id: 'F2',
        engAndChines: 'FENGTIAN',
        chineseLabel: '丰田',
        englishLabel: 'TOYOTA',
        车标: '',
        '': '',
      },
      {
        id: 'F3',
        engAndChines: 'FUTE',
        chineseLabel: '福特',
        englishLabel: 'Ford',
        车标: '',
        '': '',
      },
      {
        id: 'F4',
        engAndChines: 'FUTIAN',
        chineseLabel: '福田',
        englishLabel: 'FORLAND',
        车标: '',
        '': '',
      },
      {
        id: 'F5',
        engAndChines: 'FEIYATE',
        chineseLabel: '菲亚特',
        englishLabel: 'FIAT',
        车标: '',
        '': '',
      },
      {
        id: 'F6',
        engAndChines: 'FUDI',
        chineseLabel: '福迪',
        englishLabel: 'FODAY',
        车标: '',
        '': '',
      },
      {
        id: 'F7',
        engAndChines: 'FUTIANSHIDAI',
        chineseLabel: '福田时代',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'FB',
        engAndChines: 'FEICHIKECHE',
        chineseLabel: '飞驰客车',
        englishLabel: 'FEICHI',
        车标: '',
        '': '',
      },
      {
        id: 'FC',
        engAndChines: 'FUDA',
        chineseLabel: '福达',
        englishLabel: 'FORTA',
        车标: '',
        '': '',
      },
      {
        id: 'FD',
        engAndChines: 'FUQIQITENG',
        chineseLabel: '福汽启腾',
        englishLabel: 'Keyton',
        车标: '',
        '': '',
      },
      {
        id: 'FG',
        engAndChines: 'FEIFANQICHE',
        chineseLabel: '飞凡汽车',
        englishLabel: 'RISING AUTO',
        车标: '',
        '': '',
      },
      {
        id: 'FH',
        engAndChines: 'FEIDIEQICHE',
        chineseLabel: '飞碟汽车',
        englishLabel: 'FEIDI',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'G',
    carlist: [
      {
        id: 'G0',
        engAndChines: 'GMC',
        chineseLabel: 'GMC',
        englishLabel: 'GMC',
        车标: '',
        '': '',
      },
      {
        id: 'G1',
        engAndChines: 'GUANGQI',
        chineseLabel: '广汽',
        englishLabel: 'GAC',
        车标: '',
        '': '',
      },
      {
        id: 'G2',
        engAndChines: 'GUANGQIRIYE',
        chineseLabel: '广汽日野',
        englishLabel: 'GAC Hino',
        车标: '',
        '': '',
      },
      {
        id: 'G3',
        engAndChines: 'GUANGQIJIAO',
        chineseLabel: '广汽吉奥',
        englishLabel: 'GAC GONOW',
        车标: '',
        '': '',
      },
      {
        id: 'G4',
        engAndChines: 'GUANZHI',
        chineseLabel: '观致',
        englishLabel: 'QOROS',
        车标: '',
        '': '',
      },
      {
        id: 'G5',
        engAndChines: 'GUOJIN',
        chineseLabel: '国金',
        englishLabel: 'SINOGOLD',
        车标: '',
        '': '',
      },
      {
        id: 'G8',
        engAndChines: 'GAOHE',
        chineseLabel: '高合',
        englishLabel: 'HiPhi',
        车标: '',
        '': '',
      },
      {
        id: 'GB',
        engAndChines: 'GUOJIZHIJUN',
        chineseLabel: '国机智骏',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'H',
    carlist: [
      {
        id: 'H0',
        engAndChines: 'HAFEI',
        chineseLabel: '哈飞',
        englishLabel: 'HAFEI',
        车标: '',
        '': '',
      },
      {
        id: 'H1',
        engAndChines: 'HUANGHAI',
        chineseLabel: '黄海',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'H2',
        engAndChines: 'HANMA',
        chineseLabel: '悍马',
        englishLabel: 'Hummer',
        车标: '',
        '': '',
      },
      {
        id: 'H3',
        engAndChines: 'HAIMA',
        chineseLabel: '海马',
        englishLabel: 'Haima',
        车标: '',
        '': '',
      },
      {
        id: 'H4',
        engAndChines: 'HUAPU',
        chineseLabel: '华普',
        englishLabel: 'SMA',
        车标: '',
        '': '',
      },
      {
        id: 'H5',
        engAndChines: 'HONGQI',
        chineseLabel: '红旗',
        englishLabel: 'Hong Qi',
        车标: '',
        '': '',
      },
      {
        id: 'H6',
        engAndChines: 'HUATAI',
        chineseLabel: '华泰',
        englishLabel: 'HAWTAI MOTOR',
        车标: '',
        '': '',
      },
      {
        id: 'H9',
        engAndChines: 'HAFU',
        chineseLabel: '哈弗',
        englishLabel: 'Haval',
        车标: '',
        '': '',
      },
      {
        id: 'HA',
        engAndChines: 'HAIGE',
        chineseLabel: '海格',
        englishLabel: 'HIGER',
        车标: '',
        '': '',
      },
      {
        id: 'HF',
        engAndChines: 'HENGSHANKECHE',
        chineseLabel: '衡山客车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'HG',
        engAndChines: 'HAIQUAN',
        chineseLabel: '海全',
        englishLabel: 'HAI QUAN',
        车标: '',
        '': '',
      },
      {
        id: 'HH',
        engAndChines: 'HANTENG',
        chineseLabel: '汉腾',
        englishLabel: 'HANTENG AUTO',
        车标: '',
        '': '',
      },
      {
        id: 'HJ',
        engAndChines: 'HENGTIAN',
        chineseLabel: '恒天',
        englishLabel: 'CHTC',
        车标: '',
        '': '',
      },
      {
        id: 'HK',
        engAndChines: 'HEZHONG',
        chineseLabel: '合众',
        englishLabel: 'HOZON',
        车标: '',
        '': '',
      },
      {
        id: 'HL',
        engAndChines: 'HUAKAI',
        chineseLabel: '华凯',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'HM',
        engAndChines: 'HUALI',
        chineseLabel: '华利',
        englishLabel: 'HUALI',
        车标: '',
        '': '',
      },
      {
        id: 'HN',
        engAndChines: 'HUASONG',
        chineseLabel: '华颂',
        englishLabel: 'HUASONG',
        车标: '',
        '': '',
      },
      {
        id: 'HO',
        engAndChines: 'HUODUN',
        chineseLabel: '霍顿',
        englishLabel: 'HOLDEN',
        车标: '',
        '': '',
      },
      {
        id: 'HP',
        engAndChines: 'HUAZHONGPAI',
        chineseLabel: '华中牌',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'HQ',
        engAndChines: 'HUAXIKECHE',
        chineseLabel: '华西客车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'HR',
        engAndChines: 'HENGTONGKECHE',
        chineseLabel: '恒通客车',
        englishLabel: 'HENGTONG',
        车标: '',
        '': '',
      },
      {
        id: 'HX',
        engAndChines: 'HECHUANGQICHE',
        chineseLabel: '合创汽车',
        englishLabel: 'HUNKT',
        车标: '',
        '': '',
      },
      {
        id: 'HZ',
        engAndChines: 'HENGRUNQICHE',
        chineseLabel: '恒润汽车',
        englishLabel: 'HYCAN',
        车标: '',
        '': '',
      },
      {
        id: 'H10',
        engAndChines: 'HUACHENXINRI',
        chineseLabel: '华晨新日',
        englishLabel: 'HENGRUN',
        车标: '',
        '': '',
      },
      {
        id: 'H11',
        engAndChines: 'HUAZIQICHE',
        chineseLabel: '华梓汽车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'H13',
        engAndChines: 'HUALINGXINGMAQICHE',
        chineseLabel: '华菱星马汽车',
        englishLabel: 'HORKI',
        车标: '',
        '': '',
      },
    ],
  },
  //   {
  //     label: 'I',
  //     carlist: [],
  //   },
  {
    label: 'J',
    carlist: [
      {
        id: 'J1',
        engAndChines: 'JIEBAO',
        chineseLabel: '捷豹',
        englishLabel: 'JAGUAR',
        车标: '',
        '': '',
      },
      {
        id: 'J2',
        engAndChines: 'JINBEI',
        chineseLabel: '金杯',
        englishLabel: 'JINBEI',
        车标: '',
        '': '',
      },
      {
        id: 'J3',
        engAndChines: 'JIANGHUAI',
        chineseLabel: '江淮',
        englishLabel: 'JAC',
        车标: '',
        '': '',
      },
      {
        id: 'J4',
        engAndChines: 'JILI',
        chineseLabel: '吉利',
        englishLabel: 'GEELY',
        车标: '',
        '': '',
      },
      {
        id: 'J5',
        engAndChines: 'JIULONGQICHE',
        chineseLabel: '九龙汽车',
        englishLabel: 'JOYLONG',
        车标: '',
        '': '',
      },
      {
        id: 'J6',
        engAndChines: 'JIPU',
        chineseLabel: '吉普Jeep',
        englishLabel: 'JEEP',
        车标: '',
        '': '',
      },
      {
        id: 'J7',
        engAndChines: 'JIANGLING',
        chineseLabel: '江铃',
        englishLabel: 'JMC',
        车标: '',
        '': '',
      },
      {
        id: 'J8',
        engAndChines: 'JINLONG',
        chineseLabel: '金龙',
        englishLabel: 'KING LONG',
        车标: '',
        '': '',
      },
      {
        id: 'JD',
        engAndChines: 'JINLVKECHE',
        chineseLabel: '金旅客车',
        englishLabel: 'GOLDEN DRAGON Bus',
        车标: '',
        '': '',
      },
      {
        id: 'JE',
        engAndChines: 'JIANGHUAIKECHE',
        chineseLabel: '江淮客车',
        englishLabel: 'JAC Bus',
        车标: '',
        '': '',
      },
      {
        id: 'JG',
        engAndChines: 'JINGGONGZHONGKA',
        chineseLabel: '精功重卡',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'JI',
        engAndChines: 'JIANGLINGJITUANXINNENGYUAN',
        chineseLabel: '江铃集团新能源',
        englishLabel: 'JMEV',
        车标: '',
        '': '',
      },
      {
        id: 'JJ',
        engAndChines: 'JIANGXIWUSHILING',
        chineseLabel: '江西五十铃',
        englishLabel: 'ISUZU',
        车标: '',
        '': '',
      },
      {
        id: 'JK',
        engAndChines: 'JIHAI',
        chineseLabel: '吉海',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'JN',
        engAndChines: 'JIANGTE',
        chineseLabel: '江特',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'JU',
        engAndChines: 'JIHU',
        chineseLabel: '极狐',
        englishLabel: 'JMEV',
        车标: '',
        '': '',
      },
      {
        id: 'JV',
        engAndChines: 'JIKE',
        chineseLabel: '极氪',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'JW',
        engAndChines: 'JIXING',
        chineseLabel: '极星',
        englishLabel: 'JIAYUAN',
        车标: '',
        '': '',
      },
      {
        id: 'JX',
        engAndChines: 'JIHEQICHE',
        chineseLabel: '几何汽车',
        englishLabel: 'JIDU',
        车标: '',
        '': '',
      },
      {
        id: 'JY',
        engAndChines: 'JIAYUANQICHE',
        chineseLabel: '嘉远汽车',
        englishLabel: 'JETTA',
        车标: '',
        '': '',
      },
      {
        id: 'JZ',
        engAndChines: 'JIANGNANQICHE',
        chineseLabel: '江南汽车',
        englishLabel: 'GENESIS',
        车标: '',
        '': '',
      },
      {
        id: 'J10',
        engAndChines: 'JIEDA',
        chineseLabel: '捷达',
        englishLabel: 'JETOUR',
        车标: '',
        '': '',
      },
      {
        id: 'J11',
        engAndChines: 'JIENISAISI',
        chineseLabel: '捷尼赛思',
        englishLabel: 'GEOME',
        车标: '',
        '': '',
      },
      {
        id: 'J12',
        engAndChines: 'JIETU',
        chineseLabel: '捷途',
        englishLabel: 'ARCFOX',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'K',
    carlist: [
      {
        id: 'K0',
        engAndChines: 'KAIDILAKE',
        chineseLabel: '凯迪拉克',
        englishLabel: 'Cadillac',
        车标: '',
        '': '',
      },
      {
        id: 'K1',
        engAndChines: 'KELAISILE',
        chineseLabel: '克莱斯勒',
        englishLabel: 'CHRYSLER',
        车标: '',
        '': '',
      },
      {
        id: 'K3',
        engAndChines: 'KAIRUI',
        chineseLabel: '开瑞',
        englishLabel: 'Karry',
        车标: '',
        '': '',
      },
      {
        id: 'K4',
        engAndChines: 'KANGDI',
        chineseLabel: '康迪',
        englishLabel: 'KANDI',
        车标: '',
        '': '',
      },
      {
        id: 'K5',
        engAndChines: 'KAIMA',
        chineseLabel: '凯马',
        englishLabel: 'KAMA',
        车标: '',
        '': '',
      },
      {
        id: 'K6',
        engAndChines: 'KAERSEN',
        chineseLabel: '卡尔森',
        englishLabel: 'Carlsson',
        车标: '',
        '': '',
      },
      {
        id: 'K7',
        engAndChines: 'KAIYI',
        chineseLabel: '凯翼',
        englishLabel: 'COWIN AUTO',
        车标: '',
        '': '',
      },
      {
        id: 'K8',
        engAndChines: 'KAWEI',
        chineseLabel: '卡威',
        englishLabel: 'KAWEI',
        车标: '',
        '': '',
      },
      {
        id: 'K9',
        engAndChines: 'KAIWO',
        chineseLabel: '凯沃',
        englishLabel: 'Skywell',
        车标: '',
        '': '',
      },
      {
        id: 'KA',
        engAndChines: 'KAIYUNQICHE',
        chineseLabel: '开云汽车',
        englishLabel: 'KAIYUN MOTORS',
        车标: '',
        '': '',
      },
      {
        id: 'KB',
        engAndChines: 'KEMULE',
        chineseLabel: '克慕勒',
        englishLabel: 'Carlsson',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'L',
    carlist: [
      {
        id: 'L0',
        engAndChines: 'LANBOJINI',
        chineseLabel: '兰博基尼',
        englishLabel: 'LAMBORGHINI',
        车标: '',
        '': '',
      },
      {
        id: 'L1',
        engAndChines: 'LIFAN',
        chineseLabel: '力帆',
        englishLabel: 'LIFAN',
        车标: '',
        '': '',
      },
      {
        id: 'L2',
        engAndChines: 'LUFENG',
        chineseLabel: '陆风',
        englishLabel: 'LANDWIND',
        车标: '',
        '': '',
      },
      {
        id: 'L3',
        engAndChines: 'LUHU',
        chineseLabel: '路虎',
        englishLabel: 'LANDROVER',
        车标: '',
        '': '',
      },
      {
        id: 'L5',
        engAndChines: 'LIANHUAQICHE',
        chineseLabel: '莲花汽车',
        englishLabel: 'LOTUS',
        车标: '',
        '': '',
      },
      {
        id: 'L6',
        engAndChines: 'LINKEN',
        chineseLabel: '林肯',
        englishLabel: 'LINCOLN',
        车标: '',
        '': '',
      },
      {
        id: 'L7',
        engAndChines: 'LEIKESASI',
        chineseLabel: '雷克萨斯',
        englishLabel: 'LEXUS',
        车标: '',
        '': '',
      },
      {
        id: 'L8',
        engAndChines: 'LINGMU',
        chineseLabel: '铃木',
        englishLabel: 'SUZUKI',
        车标: '',
        '': '',
      },
      {
        id: 'L9',
        engAndChines: 'LEINUO',
        chineseLabel: '雷诺',
        englishLabel: 'RENAULT',
        车标: '',
        '': '',
      },
      {
        id: 'LA',
        engAndChines: 'LAOSILAISI',
        chineseLabel: '劳斯莱斯',
        englishLabel: 'ROLLS ROYCE',
        车标: '',
        '': '',
      },
      {
        id: 'LC',
        engAndChines: 'LINIAN',
        chineseLabel: '理念',
        englishLabel: 'Everus',
        车标: '',
        '': '',
      },
      {
        id: 'LD',
        engAndChines: 'LUDIFANGZHOU',
        chineseLabel: '陆地方舟',
        englishLabel: 'GreenWheel EV',
        车标: '',
        '': '',
      },
      {
        id: 'LE',
        engAndChines: 'LIANHEKACHE',
        chineseLabel: '联合卡车',
        englishLabel: 'C TRUCK',
        车标: '',
        '': '',
      },
      {
        id: 'LF',
        engAndChines: 'LADA',
        chineseLabel: '拉达',
        englishLabel: 'LADA',
        车标: '',
        '': '',
      },
      {
        id: 'LG',
        engAndChines: 'LANQIYA',
        chineseLabel: '蓝旗亚',
        englishLabel: 'LANCIA',
        车标: '',
        '': '',
      },
      {
        id: 'LH',
        engAndChines: 'LEIDING',
        chineseLabel: '雷丁',
        englishLabel: 'LETIN',
        车标: '',
        '': '',
      },
      {
        id: 'LJ',
        engAndChines: 'LINGKE',
        chineseLabel: '领克',
        englishLabel: 'LYNK&CO',
        车标: '',
        '': '',
      },
      {
        id: 'LL',
        engAndChines: 'LONGXI',
        chineseLabel: '龙溪',
        englishLabel: 'LONGXI',
        车标: '',
        '': '',
      },
      {
        id: 'LN',
        engAndChines: 'LEVC',
        chineseLabel: 'LEVC',
        englishLabel: 'LEVC',
        车标: '',
        '': '',
      },
      {
        id: 'LO',
        engAndChines: 'LUMMA',
        chineseLabel: 'LUMMA',
        englishLabel: 'LUMMA',
        车标: '',
        '': '',
      },
      {
        id: 'LP',
        engAndChines: 'LANTU',
        chineseLabel: '岚图',
        englishLabel: 'VOYAH',
        车标: '',
        '': '',
      },
      {
        id: 'LQ',
        engAndChines: 'LIXIANGQICHE',
        chineseLabel: '理想汽车',
        englishLabel: 'LI AUTO',
        车标: '',
        '': '',
      },
      {
        id: 'LR',
        engAndChines: 'LINGBAOQICHE',
        chineseLabel: '凌宝汽车',
        englishLabel: 'LINGBOX',
        车标: '',
        '': '',
      },
      {
        id: 'LS',
        engAndChines: 'LINGPAOQICHE',
        chineseLabel: '零跑汽车',
        englishLabel: 'LEAPMOTOR',
        车标: '',
        '': '',
      },
      {
        id: 'LT',
        engAndChines: 'LUOLUNSHI',
        chineseLabel: '罗伦士',
        englishLabel: 'Lorinser',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'M',
    carlist: [
      {
        id: 'M1',
        engAndChines: 'MAIKAILUN',
        chineseLabel: '迈凯伦',
        englishLabel: 'McLaren',
        车标: '',
        '': '',
      },
      {
        id: 'M2',
        engAndChines: 'MINI',
        chineseLabel: '迷你MINI',
        englishLabel: 'MINI',
        车标: '',
        '': '',
      },
      {
        id: 'M3',
        engAndChines: 'MASHALADI',
        chineseLabel: '玛莎拉蒂',
        englishLabel: 'MASERATI',
        车标: '',
        '': '',
      },
      {
        id: 'M4',
        engAndChines: 'MAZIDA',
        chineseLabel: '马自达',
        englishLabel: 'MAZDA',
        车标: '',
        '': '',
      },
      {
        id: 'M5',
        engAndChines: 'OUBAO',
        chineseLabel: '欧宝',
        englishLabel: 'OPEL',
        车标: '',
        '': '',
      },
      {
        id: 'M6',
        engAndChines: 'OUGE',
        chineseLabel: '讴歌',
        englishLabel: 'ACURA',
        车标: '',
        '': '',
      },
      {
        id: 'M7',
        engAndChines: 'MAN',
        chineseLabel: '曼',
        englishLabel: 'MAN',
        车标: '',
        '': '',
      },
      {
        id: 'M8',
        engAndChines: 'MUDANKECHE',
        chineseLabel: '牡丹客车',
        englishLabel: 'Mudan Bus',
        车标: '',
        '': '',
      },
      {
        id: 'MA',
        engAndChines: 'MODENGQICHE',
        chineseLabel: '摩登汽车',
        englishLabel: 'MODERN AUTO',
        车标: '',
        '': '',
      },
      {
        id: 'ME',
        engAndChines: 'MOGEN',
        chineseLabel: '摩根',
        englishLabel: 'MORGAN',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'N',
    carlist: [
      {
        id: 'N1',
        engAndChines: 'NAZHIJIE',
        chineseLabel: '纳智捷',
        englishLabel: 'LUXGEN',
        车标: '',
        '': '',
      },
      {
        id: 'N2',
        engAndChines: 'NANJUN',
        chineseLabel: '南骏',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'N4',
        engAndChines: 'NEVS',
        chineseLabel: 'NEVS',
        englishLabel: 'NEVS',
        车标: '',
        '': '',
      },
      {
        id: 'N5',
        engAndChines: 'NAZHAQICHE',
        chineseLabel: '哪吒汽车',
        englishLabel: 'NETA',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'O',
    carlist: [
      {
        id: 'O2',
        engAndChines: 'OULA',
        chineseLabel: '欧拉',
        englishLabel: 'ORA',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'P',
    carlist: [
      {
        id: 'P2',
        engAndChines: 'PENGKEQICHE',
        chineseLabel: '朋克汽车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'Q',
    carlist: [
      {
        id: 'Q0',
        engAndChines: 'QUANQIUYING',
        chineseLabel: '全球鹰',
        englishLabel: 'GLEAGLE',
        车标: '',
        '': '',
      },
      {
        id: 'Q1',
        engAndChines: 'QIRUI',
        chineseLabel: '奇瑞',
        englishLabel: 'CHERY',
        车标: '',
        '': '',
      },
      {
        id: 'Q2',
        engAndChines: 'QIYA',
        chineseLabel: '起亚',
        englishLabel: 'KIA',
        车标: '',
        '': '',
      },
      {
        id: 'Q3',
        engAndChines: 'QICHEN',
        chineseLabel: '启辰',
        englishLabel: 'Venucia',
        车标: '',
        '': '',
      },
      {
        id: 'Q4',
        engAndChines: 'QINGNIANKECHE',
        chineseLabel: '青年客车',
        englishLabel: 'YOUNG MAN',
        车标: '',
        '': '',
      },
      {
        id: 'Q5',
        engAndChines: 'QIANTU',
        chineseLabel: '前途',
        englishLabel: 'QIANTU',
        车标: '',
        '': '',
      },
      {
        id: 'Q6',
        engAndChines: 'QINGQI',
        chineseLabel: '轻骑',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'Q7',
        engAndChines: 'QILINGQICHE',
        chineseLabel: '骐铃汽车',
        englishLabel: 'JDMC',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'R',
    carlist: [
      {
        id: 'Q7',
        engAndChines: 'QILINGQICHE',
        chineseLabel: '骐铃汽车',
        englishLabel: 'JDMC',
        车标: '',
        '': '',
      },
      {
        id: 'R0',
        engAndChines: 'RICHAN',
        chineseLabel: '日产',
        englishLabel: 'NISSAN',
        车标: '',
        '': '',
      },
      {
        id: 'R1',
        engAndChines: 'RUIQI',
        chineseLabel: '瑞麒',
        englishLabel: 'Riich',
        车标: '',
        '': '',
      },
      {
        id: 'R2',
        engAndChines: 'RONGWEI',
        chineseLabel: '荣威',
        englishLabel: 'Roewe',
        车标: '',
        '': '',
      },
      {
        id: 'R3',
        engAndChines: 'RUICHI',
        chineseLabel: '瑞驰',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'R4',
        engAndChines: 'RONGDAZHIZAO',
        chineseLabel: '容大智造',
        englishLabel: 'CENNTRO',
        车标: '',
        '': '',
      },
      {
        id: 'R6',
        engAndChines: 'RUIFENGQICHE',
        chineseLabel: '瑞风汽车',
        englishLabel: 'Refine',
        车标: '',
        '': '',
      },
      {
        id: 'R7',
        engAndChines: 'RUILANQICHE',
        chineseLabel: '睿蓝汽车',
        englishLabel: 'YIVAN',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'S',
    carlist: [
      {
        id: 'S0',
        engAndChines: 'SABO',
        chineseLabel: '萨博',
        englishLabel: 'SAAB',
        车标: '',
        '': '',
      },
      {
        id: 'S1',
        engAndChines: 'SIBALU',
        chineseLabel: '斯巴鲁',
        englishLabel: 'SUBARU',
        车标: '',
        '': '',
      },
      {
        id: 'S2',
        engAndChines: 'SHUANGHUAN',
        chineseLabel: '双环',
        englishLabel: 'SHUANGHUAN',
        车标: '',
        '': '',
      },
      {
        id: 'S5',
        engAndChines: 'SIKEDA',
        chineseLabel: '斯柯达',
        englishLabel: 'SKODA',
        车标: '',
        '': '',
      },
      {
        id: 'S6',
        engAndChines: 'SANLING',
        chineseLabel: '三菱',
        englishLabel: 'MITSUBISHI',
        车标: '',
        '': '',
      },
      {
        id: 'S7',
        engAndChines: 'SHUANGLONG',
        chineseLabel: '双龙',
        englishLabel: 'SSANGYONG',
        车标: '',
        '': '',
      },
      {
        id: 'S8',
        engAndChines: 'SHANQI',
        chineseLabel: '陕汽',
        englishLabel: 'Shanxi',
        车标: '',
        '': '',
      },
      {
        id: 'S9',
        engAndChines: 'SHANGQIDATONG',
        chineseLabel: '上汽大通',
        englishLabel: 'MAXUS',
        车标: '',
        '': '',
      },
      {
        id: 'SB',
        engAndChines: 'SHIFENG',
        chineseLabel: '时风',
        englishLabel: 'SHIFENG',
        车标: '',
        '': '',
      },
      {
        id: 'SC',
        engAndChines: 'SHITONG',
        chineseLabel: '十通',
        englishLabel: 'SITOM',
        车标: '',
        '': '',
      },
      {
        id: 'SD',
        engAndChines: 'SANHUANSHITONG',
        chineseLabel: '三环十通',
        englishLabel: 'TRI RING SITOM',
        车标: '',
        '': '',
      },
      {
        id: 'SE',
        engAndChines: 'SANYIZHONGGONG',
        chineseLabel: '三一重工',
        englishLabel: 'SANY',
        车标: '',
        '': '',
      },
      {
        id: 'SG',
        engAndChines: 'SHENLONGKECHE',
        chineseLabel: '申龙客车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'SH',
        engAndChines: 'SHENWOKECHE',
        chineseLabel: '申沃客车',
        englishLabel: 'SUNWIN',
        车标: '',
        '': '',
      },
      {
        id: 'SI',
        engAndChines: 'SIMING',
        chineseLabel: '思铭',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'SJ',
        engAndChines: 'SIKANNIYA',
        chineseLabel: '斯堪尼亚',
        englishLabel: 'SCANIA',
        车标: '',
        '': '',
      },
      {
        id: 'SK',
        engAndChines: 'SMART',
        chineseLabel: 'SMART',
        englishLabel: 'SMART',
        车标: '',
        '': '',
      },
      {
        id: 'SL',
        engAndChines: 'SHAOLINKECHE',
        chineseLabel: '少林客车',
        englishLabel: 'SHAOLIN BUS',
        车标: '',
        '': '',
      },
      {
        id: 'SN',
        engAndChines: 'SHIJUN',
        chineseLabel: '时骏',
        englishLabel: 'SOJEN',
        车标: '',
        '': '',
      },
      {
        id: 'SO',
        engAndChines: 'SIWEI',
        chineseLabel: '斯威',
        englishLabel: 'SWM',
        车标: '',
        '': '',
      },
      {
        id: 'SP',
        engAndChines: 'SHANGRAOKECHE',
        chineseLabel: '上饶客车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'SQ',
        engAndChines: 'SHANGQIHONGYAN',
        chineseLabel: '上汽依维柯红岩',
        englishLabel: 'HONGYAN',
        车标: '',
        '': '',
      },
      {
        id: 'SR',
        engAndChines: 'SHANGQIYUEJIN',
        chineseLabel: '上汽跃进',
        englishLabel: 'YUEJIN',
        车标: '',
        '': '',
      },
      {
        id: 'SV',
        engAndChines: 'SHUCHIKECHE',
        chineseLabel: '舒驰客车',
        englishLabel: 'SHUCHI BUS',
        车标: '',
        '': '',
      },
      {
        id: 'SX',
        engAndChines: 'SRMXINYUAN',
        chineseLabel: 'SRM鑫源',
        englishLabel: 'SALEEN',
        车标: '',
        '': '',
      },
      {
        id: 'SY',
        engAndChines: 'SAILISI',
        chineseLabel: '赛力斯',
        englishLabel: 'SERES',
        车标: '',
        '': '',
      },
      {
        id: 'SZ',
        engAndChines: 'SHALONGQICHE',
        chineseLabel: '沙龙汽车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'S10',
        engAndChines: 'SHANQITONGJIA',
        chineseLabel: '陕汽通家',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'S12',
        engAndChines: 'SHENZHOU',
        chineseLabel: '神州',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'S13',
        engAndChines: 'SIHAO',
        chineseLabel: '思皓',
        englishLabel: 'SOL',
        车标: '',
        '': '',
      },
      {
        id: 'S14',
        engAndChines: 'SUDA',
        chineseLabel: '速达',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'S1B',
        engAndChines: 'SHANGHAIHUIZHONG',
        chineseLabel: '上海汇众',
        englishLabel: 'SHAC',
        车标: '',
        '': '',
      },
      {
        id: 'S1L',
        engAndChines: 'SCION',
        chineseLabel: 'Scion',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'T',
    carlist: [
      {
        id: 'T0',
        engAndChines: 'TANGJUN',
        chineseLabel: '唐骏',
        englishLabel: 'T King',
        车标: '',
        '': '',
      },
      {
        id: 'T1',
        engAndChines: 'TESILA',
        chineseLabel: '特斯拉',
        englishLabel: 'TESLA',
        车标: '',
        '': '',
      },
      {
        id: 'T2',
        engAndChines: 'TONGXINKECHE',
        chineseLabel: '同心客车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'T3',
        engAndChines: 'TENGSHI',
        chineseLabel: '腾势',
        englishLabel: 'DENZA',
        车标: '',
        '': '',
      },
      {
        id: 'T4',
        engAndChines: 'TANKE',
        chineseLabel: '坦克',
        englishLabel: 'TANK',
        车标: '',
        '': '',
      },
      {
        id: 'T5',
        engAndChines: 'TIANJIQICHE',
        chineseLabel: '天际汽车',
        englishLabel: 'ENOVATE',
        车标: '',
        '': '',
      },
    ],
  },
  //   {
  //     label: 'U',
  //     carlist: [],
  //   },
  //   {
  //     label: 'V',
  //     carlist: [],
  //   },
  {
    label: 'W',
    carlist: [
      {
        id: 'W0',
        engAndChines: 'WOERWO',
        chineseLabel: '沃尔沃',
        englishLabel: 'VOLVO',
        车标: '',
        '': '',
      },
      {
        id: 'W1',
        engAndChines: 'WEILIN',
        chineseLabel: '威麟',
        englishLabel: 'RELY',
        车标: '',
        '': '',
      },
      {
        id: 'W2',
        engAndChines: 'WULINGQICHE',
        chineseLabel: '五菱汽车',
        englishLabel: 'Wuling',
        车标: '',
        '': '',
      },
      {
        id: 'W4',
        engAndChines: 'WUSHILING',
        chineseLabel: '五十铃',
        englishLabel: 'ISUZU',
        车标: '',
        '': '',
      },
      {
        id: 'W6',
        engAndChines: 'WUZHENG',
        chineseLabel: '五征',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'W8',
        engAndChines: 'WEICHAIYINGZHI',
        chineseLabel: '潍柴英致',
        englishLabel: 'ENRANGER',
        车标: '',
        '': '',
      },
      {
        id: 'WE',
        engAndChines: 'WANXIANGKECHE',
        chineseLabel: '万向客车',
        englishLabel: 'WALD',
        车标: '',
        '': '',
      },
      {
        id: 'WF',
        engAndChines: 'WANXIANGQICHE',
        chineseLabel: '万象汽车',
        englishLabel: 'WANXIANG',
        车标: '',
        '': '',
      },
      {
        id: 'WG',
        engAndChines: 'WEIMAQICHE',
        chineseLabel: '威马汽车',
        englishLabel: 'Weltmeister',
        车标: '',
        '': '',
      },
      {
        id: 'WH',
        engAndChines: 'WEICHAIOURUI',
        chineseLabel: '潍柴欧睿',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'WI',
        engAndChines: 'WEILAI',
        chineseLabel: '蔚来',
        englishLabel: 'NIO',
        车标: '',
        '': '',
      },
      {
        id: 'WL',
        engAndChines: 'WEIPAI',
        chineseLabel: '魏牌',
        englishLabel: 'WEY',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'X',
    carlist: [
      {
        id: 'X0',
        engAndChines: 'XIANDAI',
        chineseLabel: '现代',
        englishLabel: 'HYUNDAI',
        车标: '',
        '': '',
      },
      {
        id: 'X2',
        engAndChines: 'XIALI',
        chineseLabel: '夏利',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'X3',
        engAndChines: 'XUETIELONG',
        chineseLabel: '雪铁龙',
        englishLabel: 'Citroën',
        车标: '',
        '': '',
      },
      {
        id: 'X4',
        engAndChines: 'XIYATE',
        chineseLabel: '西雅特',
        englishLabel: 'SEAT',
        车标: '',
        '': '',
      },
      {
        id: 'X5',
        engAndChines: 'XINDADI',
        chineseLabel: '新大地',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'X6',
        engAndChines: 'XUGONG',
        chineseLabel: '徐工',
        englishLabel: 'XCMG',
        车标: '',
        '': '',
      },
      {
        id: 'X8',
        engAndChines: 'XIYUKECHE',
        chineseLabel: '西域客车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'X9',
        engAndChines: 'XIWOKECHE',
        chineseLabel: '西沃客车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'XB',
        engAndChines: 'XIAOHU',
        chineseLabel: '小虎',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'XC',
        engAndChines: 'XIAOPENGQICHE',
        chineseLabel: '小鹏汽车',
        englishLabel: 'Xiaopeng Motors',
        车标: '',
        '': '',
      },
      {
        id: 'XD',
        engAndChines: 'XINJIAOQICHE',
        chineseLabel: '新吉奥汽车',
        englishLabel: 'NEW GONOW AUTO',
        车标: '',
        '': '',
      },
      {
        id: 'XF',
        engAndChines: 'XINLONGMAQICHE',
        chineseLabel: '新龙马汽车',
        englishLabel: 'NLM MOTOR',
        车标: '',
        '': '',
      },
      {
        id: 'XG',
        engAndChines: 'XINTEQICHE',
        chineseLabel: '新特汽车',
        englishLabel: 'SITECH',
        车标: '',
        '': '',
      },
      {
        id: 'XH',
        engAndChines: 'XINGTU',
        chineseLabel: '星途',
        englishLabel: 'EXEED',
        车标: '',
        '': '',
      },
      {
        id: 'XN',
        engAndChines: 'XUEFOLAN',
        chineseLabel: '雪佛兰',
        englishLabel: 'Chevrolet',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'Y',
    carlist: [
      {
        id: 'Y0',
        engAndChines: 'YINGFEINIDI',
        chineseLabel: '英菲尼迪',
        englishLabel: 'INFINITI',
        车标: '',
        '': '',
      },
      {
        id: 'Y1',
        engAndChines: 'YIQI',
        chineseLabel: '一汽',
        englishLabel: 'FAW',
        车标: '',
        '': '',
      },
      {
        id: 'Y2',
        engAndChines: 'YIWEIKE',
        chineseLabel: '依维柯',
        englishLabel: 'IVECO',
        车标: '',
        '': '',
      },
      {
        id: 'Y3',
        engAndChines: 'YINGTIAN',
        chineseLabel: '英田',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'Y7',
        engAndChines: 'YUTONGKECHE',
        chineseLabel: '宇通客车',
        englishLabel: 'YUTONG',
        车标: '',
        '': '',
      },
      {
        id: 'Y8',
        engAndChines: 'YUSHENG',
        chineseLabel: '驭胜',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'Y9',
        engAndChines: 'YANTAI',
        chineseLabel: '燕台',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'YA',
        engAndChines: 'YAXING',
        chineseLabel: '亚星',
        englishLabel: 'ASIASTAR',
        车标: '',
        '': '',
      },
      {
        id: 'YB',
        engAndChines: 'YEMA',
        chineseLabel: '野马',
        englishLabel: 'MUSTANG',
        车标: '',
        '': '',
      },
      {
        id: 'YC',
        engAndChines: 'YONGYUAN',
        chineseLabel: '永源',
        englishLabel: 'JONWAY',
        车标: '',
        '': '',
      },
      {
        id: 'YE',
        engAndChines: 'YUJIE',
        chineseLabel: '御捷',
        englishLabel: 'YOGOMO',
        车标: '',
        '': '',
      },
      {
        id: 'YF',
        engAndChines: 'YITUOZHONGKA',
        chineseLabel: '一拖重卡',
        englishLabel: 'YTO Truck',
        车标: '',
        '': '',
      },
      {
        id: 'YN',
        engAndChines: 'YASHENGQICHE',
        chineseLabel: '雅升汽车',
        englishLabel: 'YASHENG',
        车标: '',
        '': '',
      },
      {
        id: 'YQ',
        engAndChines: 'YINLONGXINNENGYUAN',
        chineseLabel: '银隆新能源',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'YR',
        engAndChines: 'YUANCHENGQICHE',
        chineseLabel: '远程汽车',
        englishLabel: 'FARIZON AUTO',
        车标: '',
        '': '',
      },
      {
        id: 'YS',
        engAndChines: 'YUNDU',
        chineseLabel: '云度',
        englishLabel: 'YUDO',
        车标: '',
        '': '',
      },
      {
        id: 'YT',
        engAndChines: 'YUNQUEQICHE',
        chineseLabel: '云雀汽车',
        englishLabel: 'Lark Auto',
        车标: '',
        '': '',
      },
    ],
  },
  {
    label: 'Z',
    carlist: [
      {
        id: 'Z0',
        engAndChines: 'ZHONGHUA',
        chineseLabel: '中华',
        englishLabel: 'Zhonghua',
        车标: '',
        '': '',
      },
      {
        id: 'Z1',
        engAndChines: 'ZHONGTAI',
        chineseLabel: '众泰',
        englishLabel: 'ZOTYE',
        车标: '',
        '': '',
      },
      {
        id: 'Z2',
        engAndChines: 'ZHONGXING',
        chineseLabel: '中兴',
        englishLabel: 'ZXAUTO',
        车标: '',
        '': '',
      },
      {
        id: 'Z3',
        engAndChines: 'ZHONGGUOZHONGQI',
        chineseLabel: '中国重汽',
        englishLabel: 'SINOTRUK',
        车标: '',
        '': '',
      },
      {
        id: 'Z4',
        engAndChines: 'ZHONGQIWANGPAI',
        chineseLabel: '重汽王牌',
        englishLabel: 'CDW',
        车标: '',
        '': '',
      },
      {
        id: 'Z5',
        engAndChines: 'ZHONGTONG',
        chineseLabel: '中通',
        englishLabel: 'ZHONGTONG',
        车标: '',
        '': '',
      },
      {
        id: 'Z6',
        engAndChines: 'ZHIDOU',
        chineseLabel: '知豆',
        englishLabel: 'ZD',
        车标: '',
        '': '',
      },
      {
        id: 'Z7',
        engAndChines: 'ZHONGSHUN',
        chineseLabel: '中顺',
        englishLabel: 'POLARSUN',
        车标: '',
        '': '',
      },
      {
        id: 'Z8',
        engAndChines: 'ZHINUO',
        chineseLabel: '之诺',
        englishLabel: 'ZINORO',
        车标: '',
        '': '',
      },
      {
        id: 'Z9',
        engAndChines: 'ZHONGLIANZHONGKE',
        chineseLabel: '中联重科',
        englishLabel: 'ZOOMLION',
        车标: '',
        '': '',
      },
      {
        id: 'ZA',
        engAndChines: 'ZHONGQIHAOMAN',
        chineseLabel: '重汽豪曼',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'ZB',
        engAndChines: 'ZUANSHIKECHE',
        chineseLabel: '钻石客车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'ZD',
        engAndChines: 'ZHONGCHEKECHE',
        chineseLabel: '中车客车',
        englishLabel: '未找到英文名',
        车标: '',
        '': '',
      },
      {
        id: 'ZF',
        engAndChines: 'ZHIJIQICHE',
        chineseLabel: '智己汽车',
        englishLabel: 'IM',
        车标: '',
        '': '',
      },
    ],
  },
]

export { logoList }
