/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const allowMultipleToast: typeof import('vant/es')['allowMultipleToast']
  const closeDialog: typeof import('vant/es')['closeDialog']
  const closeNotify: typeof import('vant/es')['closeNotify']
  const closeToast: typeof import('vant/es')['closeToast']
  const resetDialogDefaultOptions: typeof import('vant/es')['resetDialogDefaultOptions']
  const resetNotifyDefaultOptions: typeof import('vant/es')['resetNotifyDefaultOptions']
  const resetToastDefaultOptions: typeof import('vant/es')['resetToastDefaultOptions']
  const setDialogDefaultOptions: typeof import('vant/es')['setDialogDefaultOptions']
  const setNotifyDefaultOptions: typeof import('vant/es')['setNotifyDefaultOptions']
  const setToastDefaultOptions: typeof import('vant/es')['setToastDefaultOptions']
  const showConfirmDialog: typeof import('vant/es')['showConfirmDialog']
  const showDialog: typeof import('vant/es')['showDialog']
  const showFailToast: typeof import('vant/es')['showFailToast']
  const showImagePreview: typeof import('vant/es')['showImagePreview']
  const showLoadingToast: typeof import('vant/es')['showLoadingToast']
  const showNotify: typeof import('vant/es')['showNotify']
  const showSuccessToast: typeof import('vant/es')['showSuccessToast']
  const showToast: typeof import('vant/es')['showToast']
}
